# Generated by Django 3.0.10 on 2020-09-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subjet',
            new_name='subject',
        ),
    ]
